### ISSUE TITLE
Test instructions not working

### ISSUE THREAD

**Issue by gschivley** [NREL/OpenOA#93] opened 2020-08-21 15:22 UTC
I get an error when I try to run tests with the flag `-o python_files=test/*.py`. 

```
❯ pytest -o python_files=test/*.py --cov=operational_analysis
zsh: no matches found: python_files=test/*.py
```

Is there something I'm missing? I can run tests without the flag or by doing `python setup.py test`.

Part of review (openjournals/joss-reviews#2171)

**Comment by jordanperr** [comment] 2020-08-24 15:40
Hi @gschivley, I have not run into this error yet. The python_files flag sets a relative path from the working directory to the test files, using a glob syntax to match multiple files.

If you navigate to ./test from the current directory, do you see these files? https://github.com/NREL/OpenOA/tree/master/test

**Comment by RHammond2** [comment] 2020-08-25 20:39
Hi @jordanperr I was able to reproduce this error on my end. The zsh issue is more of a mask to the problem.

In the screenshot below I temporarily ignore the zsh error to see if I can find the underlying issue. This turns out to be even more confusing because it seems to suggest that no argument is being passed to the `-o/--override-ini` flag. I double checked thatf the testing files actually exist (they do) and that the argument we're passing is correct (they are) so it's a bit uncertain what this is stemming from.

Happy to keep digging in on this, but thought I should confirm this is able to be recreated.

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/13874373/91224893-fde59b00-e6df-11ea-88a4-13b88fce7ee4.png">

Versions:
- python: 3.7.7
- pytest: 5.4.3
- pytest-cov: 2.10.0

**Comment by gschivley** [comment] 2020-08-26 12:32
@jordanperr Yes, I do have the test files and was able to run using 

```
>>> python setup.py test
```

I think that #96 will take care of the issue by adding the `pytest.ini` file. Thanks @RHammond2.

**Comment by jordanperr** [comment] 2020-08-31 23:46
I have merged in PR96 to develop. This should resolve the issue.

**Closed by jordanperr** 2020-08-31 23:46 UTC
